### ISSUE TITLE
User Story - Discover Music that was Released on my Birthday

### ISSUE THREAD

**Issue by gamerdew64** [patrickcorcoran10/Project-1#6]
## Tasks to Consider
- [ ] Create a date field that will capture the birth date of the user
- [ ] When the user submits, we will aggregate results using the billboard API
- [ ] Display the most popular songs that came out when this user was born
